<a href="https://colab.research.google.com/github/HoseinBahmany/learning-llms/blob/main/d2l/01_preliminaries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install d2l

In [2]:
import torch

In [8]:
x = torch.arange(12, dtype=torch.float32)
print(x)
print(x.shape)
print(x.numel())
X = x.reshape(3,4)
print(X)

Y = torch.zeros((2,3,4))
print(Y)

Z = torch.randn(2,3,4)
print(Z)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])
torch.Size([12])
12
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[ 1.5125, -0.4875,  1.5818,  0.3284],
         [ 0.8449,  0.1631,  0.4830,  0.7756],
         [ 1.3001, -1.3532, -1.4363,  0.4699]],

        [[-0.4404,  0.8946,  0.6226,  1.1045],
         [ 0.6364, -0.4663, -0.2551, -1.5152],
         [-0.5244, -0.7264,  0.8752,  0.7754]]])
